In [2]:
import pandas as pd
import seaborn as sb
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
hw3=pd.read_csv("/content/mtcars.csv")

In [4]:
print(hw3)

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [5]:
hw3.shape

(32, 11)

In [6]:
hw3.axes

[RangeIndex(start=0, stop=32, step=1),
 Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
        'carb'],
       dtype='object')]

In [7]:
hw3.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [8]:
hw3.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [9]:
hw3.describe()

             mpg        cyl        disp  ...         am       gear     carb
count  32.000000  32.000000   32.000000  ...  32.000000  32.000000  32.0000
mean   20.090625   6.187500  230.721875  ...   0.406250   3.687500   2.8125
std     6.026948   1.785922  123.938694  ...   0.498991   0.737804   1.6152
min    10.400000   4.000000   71.100000  ...   0.000000   3.000000   1.0000
25%    15.425000   4.000000  120.825000  ...   0.000000   3.000000   2.0000
50%    19.200000   6.000000  196.300000  ...   0.000000   4.000000   2.0000
75%    22.800000   8.000000  326.000000  ...   1.000000   4.000000   4.0000
max    33.900000   8.000000  472.000000  ...   1.000000   5.000000   8.0000

[8 rows x 11 columns]

In [11]:
hw3.groupby(['cyl','disp'])[['mpg']].describe()

            mpg
          count  mean       std   min    25%   50%    75%   max
cyl disp
4   71.1    1.0  33.9       NaN  33.9  33.90  33.9  33.90  33.9
    75.7    1.0  30.4       NaN  30.4  30.40  30.4  30.40  30.4
    78.7    1.0  32.4       NaN  32.4  32.40  32.4  32.40  32.4
    79.0    1.0  27.3       NaN  27.3  27.30  27.3  27.30  27.3
    95.1    1.0  30.4       NaN  30.4  30.40  30.4  30.40  30.4
    108.0   1.0  22.8       NaN  22.8  22.80  22.8  22.80  22.8
    120.1   1.0  21.5       NaN  21.5  21.50  21.5  21.50  21.5
    120.3   1.0  26.0       NaN  26.0  26.00  26.0  26.00  26.0
    121.0   1.0  21.4       NaN  21.4  21.40  21.4  21.40  21.4
    140.8   1.0  22.8       NaN  22.8  22.80  22.8  22.80  22.8
    146.7   1.0  24.4       NaN  24.4  24.40  24.4  24.40  24.4
6   145.0   1.0  19.7       NaN  19.7  19.70  19.7  19.70  19.7
    160.0   2.0  21.0  0.000000  21.0  21.00  21.0  21.00  21.0
    167.6   2.0  18.5  0.989949  17.8  18.15  18.5  18.85  19.2
    225.0   1.0  18.1       NaN  18.1  18.10  18.1  18.10  18.1
    258.0   1.0  21.4       NaN  21.4  21.40  21.4  21.40  21.4
8   275.8   3.0  16.3  1.053565  15.2  15.80  16.4  16.85  17.3
    301.0   1.0  15.0       NaN  15.0  15.00  15.0  15.00  15.0
    304.0   1.0  15.2       NaN  15.2  15.20  15.2  15.20  15.2
    318.0   1.0  15.5       NaN  15.5  15.50  15.5  15.50  15.5
    350.0   1.0  13.3       NaN  13.3  13.30  13.3  13.30  13.3
    351.0   1.0  15.8       NaN  15.8  15.80  15.8  15.80  15.8
    360.0   2.0  16.5  3.111270  14.3  15.40  16.5  17.60  18.7
    400.0   1.0  19.2       NaN  19.2  19.20  19.2  19.20  19.2
    440.0   1.0  14.7       NaN  14.7  14.70  14.7  14.70  14.7
    460.0   1.0  10.4       NaN  10.4  10.40  10.4  10.40  10.4
    472.0   1.0  10.4       NaN  10.4  10.40  10.4  10.40  10.4

In [13]:
hw3[hw3['cyl']>3]

     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [14]:
hw3['cyl']>4

0      True
1      True
2     False
3      True
4      True
5      True
6      True
7     False
8     False
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17    False
18    False
19    False
20    False
21     True
22     True
23     True
24     True
25    False
26    False
27    False
28     True
29     True
30     True
31    False
Name: cyl, dtype: bool

In [16]:
hw3.skew(
)

mpg     0.672377
cyl    -0.192261
disp    0.420233
hp      0.799407
drat    0.292780
wt      0.465916
qsec    0.406347
vs      0.264542
am      0.400809
gear    0.582309
carb    1.157091
dtype: float64

In [18]:
hw3.kurtosis()

mpg    -0.022006
cyl    -1.762794
disp   -1.067523
hp      0.275212
drat   -0.450432
wt      0.416595
qsec    0.864931
vs     -2.063273
am     -1.966550
gear   -0.895292
carb    2.020059
dtype: float64

In [19]:
hw3.ndim

2

In [20]:
hw3.values

array([[ 21.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.62 ,  16.46 ,
          0.   ,   1.   ,   4.   ,   4.   ],
       [ 21.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.875,  17.02 ,
          0.   ,   1.   ,   4.   ,   4.   ],
       [ 22.8  ,   4.   , 108.   ,  93.   ,   3.85 ,   2.32 ,  18.61 ,
          1.   ,   1.   ,   4.   ,   1.   ],
       [ 21.4  ,   6.   , 258.   , 110.   ,   3.08 ,   3.215,  19.44 ,
          1.   ,   0.   ,   3.   ,   1.   ],
       [ 18.7  ,   8.   , 360.   , 175.   ,   3.15 ,   3.44 ,  17.02 ,
          0.   ,   0.   ,   3.   ,   2.   ],
       [ 18.1  ,   6.   , 225.   , 105.   ,   2.76 ,   3.46 ,  20.22 ,
          1.   ,   0.   ,   3.   ,   1.   ],
       [ 14.3  ,   8.   , 360.   , 245.   ,   3.21 ,   3.57 ,  15.84 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 24.4  ,   4.   , 146.7  ,  62.   ,   3.69 ,   3.19 ,  20.   ,
          1.   ,   0.   ,   4.   ,   2.   ],
       [ 22.8  ,   4.   , 140.8  ,  95.   ,   3.92 ,   3.15 ,  22.9  ,
          1.   ,   0.   ,   4.   ,   2.   ],
       [ 19.2  ,   6.   , 167.6  , 123.   ,   3.92 ,   3.44 ,  18.3  ,
          1.   ,   0.   ,   4.   ,   4.   ],
       [ 17.8  ,   6.   , 167.6  , 123.   ,   3.92 ,   3.44 ,  18.9  ,
          1.   ,   0.   ,   4.   ,   4.   ],
       [ 16.4  ,   8.   , 275.8  , 180.   ,   3.07 ,   4.07 ,  17.4  ,
          0.   ,   0.   ,   3.   ,   3.   ],
       [ 17.3  ,   8.   , 275.8  , 180.   ,   3.07 ,   3.73 ,  17.6  ,
          0.   ,   0.   ,   3.   ,   3.   ],
       [ 15.2  ,   8.   , 275.8  , 180.   ,   3.07 ,   3.78 ,  18.   ,
          0.   ,   0.   ,   3.   ,   3.   ],
       [ 10.4  ,   8.   , 472.   , 205.   ,   2.93 ,   5.25 ,  17.98 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 10.4  ,   8.   , 460.   , 215.   ,   3.   ,   5.424,  17.82 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 14.7  ,   8.   , 440.   , 230.   ,   3.23 ,   5.345,  17.42 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 32.4  ,   4.   ,  78.7  ,  66.   ,   4.08 ,   2.2  ,  19.47 ,
          1.   ,   1.   ,   4.   ,   1.   ],
       [ 30.4  ,   4.   ,  75.7  ,  52.   ,   4.93 ,   1.615,  18.52 ,
          1.   ,   1.   ,   4.   ,   2.   ],
       [ 33.9  ,   4.   ,  71.1  ,  65.   ,   4.22 ,   1.835,  19.9  ,
          1.   ,   1.   ,   4.   ,   1.   ],
       [ 21.5  ,   4.   , 120.1  ,  97.   ,   3.7  ,   2.465,  20.01 ,
          1.   ,   0.   ,   3.   ,   1.   ],
       [ 15.5  ,   8.   , 318.   , 150.   ,   2.76 ,   3.52 ,  16.87 ,
          0.   ,   0.   ,   3.   ,   2.   ],
       [ 15.2  ,   8.   , 304.   , 150.   ,   3.15 ,   3.435,  17.3  ,
          0.   ,   0.   ,   3.   ,   2.   ],
       [ 13.3  ,   8.   , 350.   , 245.   ,   3.73 ,   3.84 ,  15.41 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 19.2  ,   8.   , 400.   , 175.   ,   3.08 ,   3.845,  17.05 ,
          0.   ,   0.   ,   3.   ,   2.   ],
       [ 27.3  ,   4.   ,  79.   ,  66.   ,   4.08 ,   1.935,  18.9  ,
          1.   ,   1.   ,   4.   ,   1.   ],
       [ 26.   ,   4.   , 120.3  ,  91.   ,   4.43 ,   2.14 ,  16.7  ,
          0.   ,   1.   ,   5.   ,   2.   ],
       [ 30.4  ,   4.   ,  95.1  , 113.   ,   3.77 ,   1.513,  16.9  ,
          1.   ,   1.   ,   5.   ,   2.   ],
       [ 15.8  ,   8.   , 351.   , 264.   ,   4.22 ,   3.17 ,  14.5  ,
          0.   ,   1.   ,   5.   ,   4.   ],
       [ 19.7  ,   6.   , 145.   , 175.   ,   3.62 ,   2.77 ,  15.5  ,
          0.   ,   1.   ,   5.   ,   6.   ],
       [ 15.   ,   8.   , 301.   , 335.   ,   3.54 ,   3.57 ,  14.6  ,
          0.   ,   1.   ,   5.   ,   8.   ],
       [ 21.4  ,   4.   , 121.   , 109.   ,   4.11 ,   2.78 ,  18.6  ,
          1.   ,   1.   ,   4.   ,   2.   ]])

In [22]:
hw3.count()

mpg     32
cyl     32
disp    32
hp      32
drat    32
wt      32
qsec    32
vs      32
am      32
gear    32
carb    32
dtype: int64